version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-yo-app
    command: go run main.go
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - redis
