version: "3.8"
services:
  app:
    build:
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - USERNAME=arichard
      context: .
      dockerfile: Dockerfile
    container_name: conductor_orchestration_notification
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
    links:
      - db
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    container_name: conductor_orchestration_notification_db
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - conductor_orchestration_notification_volume:/var/lib/postgresql/data
volumes:
  conductor_orchestration_notification_volume:
    driver: local