version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twit_api
    env_file:
      - ".env"
    ports:
      - "9090:9090"
    depends_on:
      - db
    volumes:
      - ./:/app
    links:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    container_name: twit_db
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - twit_db:/var/lib/postgresql/data
volumes:
  twit_db:
    driver: local