version: "3.8"
services:
  web-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: twit_api_test
    env_file:
      - "test.env"
    ports:
      - "9090:9090"
    depends_on:
      - db-test
    volumes:
      - ./:/app
    links:
      - db
  db-test:
    image: postgres:13
    ports:
      - "5432:5432"
    container_name: twit_db_test
    env_file:
      - "test.env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - twit_db_test:/var/lib/postgresql/data
volumes:
  twit_db_test:
    driver: local
